#version 130

uniform mat4 world_matrix;
uniform mat4 view_matrix;
uniform mat4 projection_matrix;

in vec3 position;
in vec3 normal;

out vec3 vertex_normal;
out vec3 world_position;

void main(void)
{
	world_position = (world_matrix * vec4(position, 1)).xyz;
	vertex_normal = mat3(world_matrix) * normal;
	gl_Position = projection_matrix * view_matrix * vec4(world_position, 1);
}
