#define BULLETSHARP_VERSION_MAJOR 2
#define BULLETSHARP_VERSION_MINOR 83
#define BULLETSHARP_VERSION_REVISION 7
#define BULLETSHARP_VERSION_STRING "2.83.7"
#define BULLETSHARP_COPYRIGHT "Copyright (C) Andres Traks 2009-2016"
