#define BULLETSHARP_VERSION_MAJOR 2
#define BULLETSHARP_VERSION_MINOR 86
#define BULLETSHARP_VERSION_REVISION 1
#define BULLETSHARP_VERSION_REVISION2 0
#define BULLETSHARP_VERSION_STRING "2.86.1"
#define BULLETSHARP_COPYRIGHT "Copyright (C) Andres Traks 2009-2017"
